### ISSUE TITLE
Quotation marks getting picked up by DotEnv

### ISSUE THREAD

**Issue by OzzyTheGiant** [bolorundurowb/dotenv.net#13]
If I have a variable with a value that has a space in it, I have to use double quotation marks. However, when running this in ASP.NET Core 2.2, DotEnv includes the quotations marks in variable rather than understanding it's marking the start and end of the string. could it be possible to fix this bug? I require quotation marks for file paths in which folders have spaces, and I say it's a bug because this type of value is handled well in other dotenv package equivalents in other languages.

**Comment by bolorundurowb** [comment]
@OzzyTheGiant can you provide an example `.env` file?
