### ISSUE TITLE
Autofac Dependency should be in another package

### ISSUE THREAD

**Issue by BlowaXD** [bolorundurowb/dotenv.net#25]
Hi,

You recently decided to provide easy DI for your package, the thing is, you provided your package with direct dependency of AutoFac on version 2.0+

Do you think you can split the AutoFac DI extensions to another package ? like dotenv.net.AutoFac

Thanks for your library.

**Comment by bolorundurowb** [comment]
Thanks @BlowaXD , I see the point you are making and would get right on that

**Comment by BlowaXD** [comment]
Thanks 😊
It was mostly because I'd like to reduce the size of my docker images but I still want to use your library.

**Comment by bolorundurowb** [comment]
These are the DI packages @BlowaXD 
https://www.nuget.org/packages/dotenv.net.DependencyInjection.Microsoft
https://www.nuget.org/packages/dotenv.net.DependencyInjection.Autofac/

**Comment by BlowaXD** [comment]
Thanks gonna update it tonight :) !
