### ISSUE TITLE
Can retrieve a string

### ISSUE THREAD

**Issue by Lexa013** [bolorundurowb/dotenv.net#32]
![image](https://user-images.githubusercontent.com/48451588/98831316-b5668f80-243b-11eb-958d-8d38d5782a52.png)
![image](https://user-images.githubusercontent.com/48451588/98831356-c1eae800-243b-11eb-8212-6977b33b6230.png)

`Exception non gérée : System.Exception: Value could not be retrieved.
   à dotenv.net.Utilities.EnvReader.GetStringValue(String key)
   à AccessBot.Program.Main(String[] args) dans D:\Developement\C#\Projects\AccessBot\AccessBot\Program.cs:ligne 17
`

i cant retrieve my value, any idea please ?

**Comment by Gounlaf** [comment]
You have to call `DotEnv.AutoConfig();` before. It will populate the `Environment` with values from your `.env` file

**Comment by austinschrader** [comment]
> You have to call `DotEnv.AutoConfig();` before. It will populate the `Environment` with values from your `.env` file

I have the same error as OP and I have included DotEnv.AutoConfig(); 

![image](https://user-images.githubusercontent.com/20011035/102560195-82d93380-4086-11eb-9319-96faadbe521c.png)
![image](https://user-images.githubusercontent.com/20011035/102560212-92587c80-4086-11eb-886e-ca6393d1782a.png)

Do you happen to know why that would be?

**Comment by Lexa013** [comment]
No Ida

Le ven. 18 déc. 2020 à 01:40, Austin Schrader <notifications@github.com> a
écrit :

**Comment by bolorundurowb** [comment]
@Lexa013 there are two things in play here. 
1. `AutoConfig` searches up three levels from the location of the library which means the topmost folder it'll search is the `bin` folder.
2. `envReader.GetStringValue` would throw an exception if it can't find a value for the given key but `envReader.TrygetStringValue` is the exception-safe option.

To address the first point here though, in the next release, I would be increasing the number of levels to search from 3 to 4 to handle the nested build format of MsBuild meaning the topmost folder searched would now  be the project folder and not the `bin`. 

An immediate solution to the issue yourself and @austinschrader  are having would be changing `DotEnv.AutoConfig()` to `DotEnv.AutoConfig(4)`
