### ISSUE TITLE
Getting error "The file path cannot be null, empty or whitespace. (Parameter 'envFilePath')"

### ISSUE THREAD

**Issue by Arrow7000** [bolorundurowb/dotenv.net#40]
I keep getting the error `The file path cannot be null, empty or whitespace. (Parameter 'envFilePath')`.

I'm using it from F# like this:

```fsharp
[<EntryPoint>]
let main _ =
    let opts =
        new DotEnvOptions(probeForEnv = true, probeLevelsToSearch = 2, ignoreExceptions = false)

    DotEnv.Load(opts)
```
As far as I can tell from the docs `envFilePaths` isn't a required parameter and either way it's `envFilePath` in the singular that's in the error message so it looks to me like a bug.

**Comment by Gounlaf** [comment]
Have same issue here, only when the application is packaged (standalone app, C#, .NET Core 5, running in Docker).
Running the application directly (I'm using JetBrains Rider), it does work as expected
